### ISSUE TITLE
Not able to make twin work with Storybook

### ISSUE THREAD

**Issue by kouliavtsev** [ben-rogerson/twin.examples#1]
I have configured twin macro to work with nextjs and emotion. It works great!

However, when I try to add the component to Storybook I get the following error:

```
RROR in ./components/Apple.js
Module not found: Error: Can't resolve '@emotion/styled-base' in '/Users/antonkouliavtsev/Projects/clients/stoked/nucleus-tenant/web/client/components'
 @ ./components/Apple.js 1:0-44 17:12-20
 @ ./stories/Apple.stories.js
 @ ./stories sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|ts|tsx))$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/defaultParameters.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
```

I am a bit confused on how to get this configured, since setting emotion through twin macro is slightly different than doing the standalone setup.

**Comment by ben-rogerson** [comment]
I've just pushed up a brand new [storybook + emotion demo](https://github.com/ben-rogerson/twin.examples/tree/master/storybook-emotion) so perhaps take a look at it for an idea on the setup.

> `Error: Can't resolve '@emotion/styled-base'`

I found this error comes from `@emotion/babel-preset-css-prop` which doesn’t work with Emotion@11+ outside of a Next.js environment.

To fix this you can make a custom storybook babel config in `.storybook` that doesn't use`@emotion/babel-preset-css-prop`.
That's the technique I've used in [the demo](https://github.com/ben-rogerson/twin.examples/tree/master/storybook-emotion).
