### ISSUE TITLE
Broken react emotion example

### ISSUE THREAD

**Issue by george-dotdev** [ben-rogerson/twin.examples#10]
Getting this error on the codesandbox emotion react example:
https://codesandbox.io/embed/github/ben-rogerson/twin.examples/tree/master/react-emotion?file=/src/App.js

![image](https://user-images.githubusercontent.com/41870207/100954723-3ca1b180-3569-11eb-824c-9f9940814e3d.png)

**Comment by ben-rogerson** [comment]
I'm seeing this error across a few sandboxes. I've filed an [issue with CodeSandbox](https://github.com/codesandbox/codesandbox-client/issues/5216), let's see how we go.

**Comment by ben-rogerson** [comment]
Fixed-  it due to the missing tailwindcss dependency
