### ISSUE TITLE
TypeError: twin_macro__WEBPACK_IMPORTED_MODULE_2__.theme is not a function

### ISSUE THREAD

**Issue by noadek** [ben-rogerson/twin.examples#106]
Initially, I followed the steps for adding twin.macro into nextjs for my existing project and I spent days running into multiple errors like MODULE_NOT_FOUND 'fs', 'os', 'crypto' etc. after adding some recommendations to my next.config 

```
module.exports = {
  webpack: config => {
    // Unset client-side javascript that only works server-side
    config.resolve.fallback = { fs: false, module: false, path: false, os: false, crypto:false };
    return config
  },
};
```

I was able to run the app but then, I got the error "twin_macro__WEBPACK_IMPORTED_MODULE_2__.theme is not a function" after so many hours of trying to fix this, I decided to use the next-styled-components-typescript example so I don't get any interference since my workspace was an nx monorepo.

I downloaded the **next-styled-components-typescript** example installed the dependencies and ran the app but again I got the famous
```
error - ./node_modules/cosmiconfig/dist/readFile.js:9:0
Module not found: Can't resolve 'fs'
```

So I added the module exports config above and tried again I get 

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - ./node_modules/babel-plugin-macros/dist/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/import-fresh/index.js
Critical dependency: the request of a dependency is an expression
```

and after the app reloads on the browser I get the following errors
```
...
 4 | const CustomStyles = createGlobalStyle({
  5 |   body: {
> 6 |     WebkitTapHighlightColor: theme`colors.electric`,
    |                                   ^
  7 |     ...tw`antialiased`,
  8 |   },
  9 | })
TypeError: twin_macro__WEBPACK_IMPORTED_MODULE_2__.theme is not a function
    at eval (webpack-internal:///./styles/GlobalStyles.tsx:16:79)
...
```

My current node version is 
node v16.16.0
npm 8.11.0

**Comment by benrudolphWSP** [comment]
@noadek How did you fix this? I am running into the same issue.

**Comment by noadek** [comment]
> @noadek How did you fix this? I am running into the same issue.

Lucky for me, it's a new project so I settled with using the nextjs example project https://github.com/ben-rogerson/twin.examples/tree/master/next-styled-components-typescript

**Comment by HarveyNgo** [comment]
in my case, because "pages", "styles" folders put inside folder "src" that cause can not find "theme" function,
to fix it, in withTwin.js, update :

path.resolve(__dirname, 'styles')-->  path.resolve(__dirname, 'src/styles'),
path.resolve(__dirname, 'pages') --> path.resolve(__dirname, 'src/pages')


Hope this help
