### ISSUE TITLE
Twin example for vite-emotion-typescript - trying to add babel-plugin-twin

### ISSUE THREAD

**Issue by shemayas** [ben-rogerson/twin.examples#107]
Hi,
Using Twin with Vite (followed the vite-emotion-typescript)
I'm trying to add the babel-plugin-twin so I will not need to import twin in every component.

after installing and adding to vite config like this:
```js
...
babel: {
        plugins: [
          'babel-plugin-macros',
          [
            '@emotion/babel-plugin-jsx-pragmatic',
            {
              export: 'jsx',
              import: '__cssprop',
              module: '@emotion/react',
            },
          ],
          [
            '@babel/plugin-transform-react-jsx',
            { pragma: '__cssprop' },
            'twin.macro',
          ],
          ['babel-plugin-twin', { debug: true }],
        ],
      },
...
```
I get an error in the browser console:
![image](https://user-images.githubusercontent.com/11064714/205485329-9ae4d8e0-0a42-431b-8926-810037dd70e4.png)

**Comment by ben-rogerson** [comment]
Hey there

Check out [the official installation instructions](https://github.com/ben-rogerson/babel-plugin-twin#installation) - could you let me know if that works?

**Comment by shemayas** [comment]
I missed the note:

> Note: You must add "babel-plugin-twin" before "babel-plugin-macros" in the plugins array.

Now all works, thank you!
