### ISSUE TITLE
Snowpack React Emotion: Error upon clean startup

### ISSUE THREAD

**Issue by antoniobrandao** [ben-rogerson/twin.examples#11]
Just to report a problem running one of the examples.
Tried with Node 12.20 and 14.15

What I did:

- a fresh download of `snowpack-react-emotion`
- Then `yarn`
- Then `yarn start`

Results:

- dependencies installed correctly without errors
- server started well without errors in the console either
- the page was served at http://localhost:8080
- the page failed to render and showed an error: base.min.css.proxy.js:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.

I did not install anything else or do any changes.

Searching Google didn't yield any tangible info so I share this here.

I also tried `cra-emotion` and that one worked fine!

**Comment by ben-rogerson** [comment]
Thanks for the report, I've tested locally and didn't have any issues.
I did find that the tailwindcss version was still on v1, so I've incremented - perhaps give that a try?

```js
{
  "dependencies": {
    "tailwindcss": "^2.0.1",
  }
}
```
