### ISSUE TITLE
Please provide instruction of how to setup Jest testing with twin

### ISSUE THREAD

**Issue by leodevbro** [ben-rogerson/twin.examples#112]
I am using this setup:
https://github.com/ben-rogerson/twin.examples/tree/master/next-styled-components-typescript

With simple Jest setup, Jest works fine for simple files with simple React components, but if the file contains `tw` import, Jest throws error something like this: `imported tw is out of context`.

Please provide an instruction, or maybe GitHub repo of setup of jest with Next.js (with SWC + TypeScript + Twin)

**Comment by ben-rogerson** [comment]
Have you checked out the [jest example](https://github.com/ben-rogerson/twin.examples/blob/b48d2afc13c6fb1f45748cf438e5a81e210d9c35/jest-testing-typescript/jest.config.js#L21), theres some config there you'll need to set.

**Comment by leodevbro** [comment]
Thanks, I'll check it out as soon as I can and will be back with feedback.

**Comment by leodevbro** [comment]
Thanks, it works with that example.

At first, the example did not work, then I added `modulePaths: ['<rootDir>/'],` in the `customJestConfig` object and now it works fine.
