### ISSUE TITLE
 tw-elements  doesn't work after update

### ISSUE THREAD

**Issue by beqramo** [ben-rogerson/twin.examples#114]
Hi,
I'm trying to add https://github.com/mdbootstrap/Tailwind-Elements to the package via plugin functionality:
```js
module.exports = {
  content: [
    './node_modules/tw-elements/dist/js/**/*.js',
  ],
  plugins: [
    require('tw-elements/dist/plugin'),
  ]
}
```
but sadly I'm getting this error after updating it to the up to date version. it is working fine on v2.8.2.

<img width="378" alt="image" src="https://user-images.githubusercontent.com/40486471/224415311-24069b01-c246-4f2c-9a61-a8a008ff458e.png">

**Comment by ben-rogerson** [comment]
Hey did you get this sorted?

Just looking at the docs, it doesn't look like there's a modal class.
https://tailwind-elements.com/docs/standard/components/modal/

Looks like they expect a data attribute added instead.

**Comment by beqramo** [comment]
Hi,
Thanks, will check.
I will check. 
Also as an other fact, after removing that package bundling speed increased 5x maybe.

I will close it for now, after checking it if anything I will reopen it.
Thank you

**Comment by ben-rogerson** [comment]
Guessing they're adding a bunch of new classes to the tailwind.config. More classes = more parsing. I've seen that improved in other libraries by only adding the modules you need but not sure if tw-elements allows that.
