### ISSUE TITLE
[vite-emotion-typescript] Could not resolve "tailwindcss/stubs/defaultConfig.stub"

### ISSUE THREAD

**Issue by ghtea** [ben-rogerson/twin.examples#115]
I followed 'vite-emotion-typescript' example but when I run 'yarn dev' 
I see following in terminal
![Screenshot 2023-03-29 at 2 25 49 PM](https://user-images.githubusercontent.com/47841931/228435437-f7faedfc-0473-4d7b-aab6-fc651a6c74b9.jpg)

**I also tried downloading twin.examples/vite-emotion-typescript/ and result was same**

**Comment by erkamdemirci** [comment]
same here, just updated next": "^13.2.4", "twin.macro": "^3.1.0" and "tailwindcss": "^3.3.0" and getting 
  
![image](https://user-images.githubusercontent.com/5718991/228488682-b1c5deba-31a1-4816-b02d-d23ee8a28fb5.png)

**Comment by ben-rogerson** [comment]
Looks like the same issue as https://github.com/ben-rogerson/twin.macro/issues/791
Use the previous tailwindcss version until then:
```shell
npm i tailwindcss@3.2.7
```

**Comment by ben-rogerson** [comment]
Fixed in [v.3.3](https://github.com/ben-rogerson/twin.macro/releases/tag/3.3.0) 🎉
