### ISSUE TITLE
This example causes next.js to fallback to Babel from SWC

### ISSUE THREAD

**Issue by elmarsto** [ben-rogerson/twin.examples#120]
Expected: 

 - Twin example supports current NextJS platform, including SWC
 

Experienced:

 - Twin example forces NextJS to fall back from SWC to Babel -- a significant change that, on larger projects, would cause significant developer-loop delay and, probably, undefined changes in compiled output; it is at least theoretically possible to break a large website in unexpected, undetectable ways.  See https://nextjs.org/docs/advanced-features/compiler

Recommendation:

 - At the very least, indicate in the README.md that there may be side effects of applying this pattern to an existing Next project, which will include slowdown and may also include broken builds, changed behaviour, and changed output.

**Comment by ben-rogerson** [comment]
Which Next.js example did you experience this issue with?

The `withTwin.js` implementation doesn't disable SWC while the `.babelrc` method does. With a .babelrc in the root, Next will notice this and disable the SWC compilation, opting for a babel alternative.
All of the `next-xxx` examples in this repo use the `withTwin.js` setup so I'm wondering if I've missed updating a readme somewhere?

**Comment by elmarsto** [comment]
Sorry -- I think I misunderstood what was going on at my end.
