### ISSUE TITLE
Tailwind + Styled Components + SWC (TurboPack) + NextJs (no babel)

### ISSUE THREAD

**Issue by MrOxMasTer** [ben-rogerson/twin.examples#123]
Hello, there was such a problem that I wanted to combine tailwind and styled Components. I think, wow, there's even an instruction, but the problem is that it's for babel. 
I use Turbopack, but it does not support babel yet https://turbo.build/pack/docs/features/javascript
, and I use a completely different way to add to extjs from the official website. 
https://nextjs.org/docs/app/building-your-application/styling/css-in-js#styled-components
How can I combine Styled Components and tailwind without babel?

**Comment by ben-rogerson** [comment]
Twin provides functionality within a babel environment so we haven't any information on the non-babel path.
