### ISSUE TITLE
It can run but why it will appear error ?

### ISSUE THREAD

**Issue by SearchingForSea** [ben-rogerson/twin.examples#126]
![image](https://github.com/ben-rogerson/twin.examples/assets/104902367/b0b1f7c4-db73-4145-936c-ef64a5744dc9)

**Comment by ben-rogerson** [comment]
You'll need to setup the imports - see the `twin.d.ts` files in the typescript repositories.
See [here](https://github.com/ben-rogerson/twin.examples/blob/master/next-emotion-typescript/types/twin.d.ts) or [here](https://github.com/ben-rogerson/twin.examples/tree/master/next-styled-components-typescript#add-typescript-types) for setup details. You'll also need to tell typescript about the file, see the tsconfig file in each repo for that.
