### ISSUE TITLE
Using the next example - styling `next/link` doesn't appear to work

### ISSUE THREAD

**Issue by mwarger** [ben-rogerson/twin.examples#13]
I've used `npx degit https://github.com/ben-rogerson/twin.examples/next-emotion folder-name` and have not been able to style the Link imported from Next.  Thinks I have tried include:

```
import tw from 'twin.macro'
import NextLink from 'next/link'

export const Link = tw(NextLink)`px-4 py-2 text-sm font-medium text-white`

```

```
import { styled } from 'twin.macro'
import NextLink from 'next/link'

export const Link = styled(NextLink)(() => [
  `px-4 py-2 text-sm font-medium text-white`
])

```

I have also tried using the `css` or `tw` props directly on the Link component.  

Please let me know if I'm doing something wrong here, I'm new to this.  Thanks!

**Comment by ben-rogerson** [comment]
All good, this has bitten me before also!

The `NextLink` component is a little weird, it doesn't apply styles in a way you'd assume.
The official way to style your links is like this:

```js
import tw, { styled } from 'twin.macro'
import NextLink from 'next/link'

const MyLink = tw.a`px-4 py-2 text-sm font-medium text-white`
// or
// const MyLink = styled.a(tw`px-4 py-2 text-sm font-medium text-white`)

const Link = () => (
    <NextLink href="/login" passHref>
        <MyLink>Home</MyLink>
    </NextLink>
)
```
