### ISSUE TITLE
[Request] Example WMR with twin.macro

### ISSUE THREAD

**Issue by sprabowo** [ben-rogerson/twin.examples#16]
Hi Ben @ben-rogerson ,

Thanks for making twin example. I see [wmr](https://github.com/preactjs/wmr) is using preact as well. when i install goober in WMR it's fine. do you have tricks to add twin.macro in WMR + Goober/Styled Component?

Thanks

**Comment by ben-rogerson** [comment]
WMR doesn't support babel-plugin-macros. Once support has been added then we can look at the support but I'm not aware of any plans.
