### ISSUE TITLE
Next.js + Emotion Example Causes FOUC

### ISSUE THREAD

**Issue by femetrie** [ben-rogerson/twin.examples#19]
Using the`CacheProvider` with Next and Emotion causes the built site to not produce CSS files or inline CSS in the HTML output.

The fix is to remove the `CacheProvider` from `_app.js` entirely, which I discovered in this PR comment: https://github.com/vercel/next.js/pull/17651#discussion_r501413938. The built HTML for SSR / SSG pages now contains inlined CSS.

**Comment by ben-rogerson** [comment]
I've got this on my list to update, cheers for the reminder

**Comment by ben-rogerson** [comment]
I've now [updated the instructions](https://github.com/ben-rogerson/twin.examples/commit/e79378863d8556913207b88805e186804fb1236e) to match the repo 👍
