### ISSUE TITLE
Add further component library examples

### ISSUE THREAD

**Issue by JPrisk** [ben-rogerson/twin.examples#20]
[nwb](https://github.com/insin/nwb#react-components-and-libraries) & [neutrinojs](https://neutrinojs.org/packages/react-components/) are two popular tools used by component library authors to create and publish react components for distribution.

I experimented with adding twin.macro but received the following errors:

```
in ./node_modules/path-type/index.js
Module not found: Error: Can't resolve 'fs' in '.../node_modules/path-type'

in ./node_modules/resolve-from/index.js
Module not found: Error: Can't resolve 'fs' in '.../node_modules/resolve-from

in ./node_modules/resolve/lib/async.js
Module not found: Error: Can't resolve 'fs' in '.../node_modules/resolve/lib'

in ./node_modules/resolve/lib/sync.js
Module not found: Error: Can't resolve 'fs' in '.../node_modules/resolve/lib'

in ./node_modules/twin.macro/macro.js
Module not found: Error: Can't resolve 'fs' in '.../node_modules/twin.macro'

in ./node_modules/twin.macro/node_modules/cosmiconfig/dist/readFile.js
Module not found: Error: Can't resolve 'fs' in '.../node_modules/twin.macro/node_modules/cosmiconfig/dist'

in ./node_modules/resolve-from/index.js
Module not found: Error: Can't resolve 'module' in '.../node_modules/resolve-from'
```

would love to help out but my knowledge is limited in this space

**Comment by JPrisk** [comment]
Ah, thanks @ben-rogerson - had I seen the Rollup example it would have saved me a bit of time. I ended up using [create-react-library](https://github.com/transitive-bullshit/create-react-library) which was compatible with the module structure that you are using with twin

**Comment by ben-rogerson** [comment]
that's probably the better option anyway, more features :)

**Comment by mmmoli** [comment]
I'm utterly stumped on trying get `twin.macro` + `emotion` + `nx-workspaces` to play nice with each other.

I've tried following the [advice of @ben-rogerson](https://github.com/ben-rogerson/twin.examples/tree/master/component-library-styled-components) to no avail:

> The trick is to use Babel to compile typescript (rather than rollup-plugin-typescript and rely on typescript for type checking and generation of declaration files.

Here's my checklist

- [x] Add "macros" to every .babelrc file I can find
- [x] Match the [`.babelrc` from the "component-library-styled-components" example](https://github.com/ben-rogerson/twin.examples/blob/master/component-library-styled-components/packages/components/.babelrc)
- [x] Follow the twin setup guide for every "app" in the nx workspace – currently `app:web (React)` and `lib:ui (React)`
- [x] Try making the nx react lib (called "ui") "buildable"
- [x] Use the [tsconfig.js from the "component-library-styled-components" example](https://github.com/ben-rogerson/twin.examples/blob/master/component-library-styled-components/packages/components/tsconfig.json)

I seem to get the same error:

`MacroError: The macro you imported from "undefined" is being executed outside the context of compilation with babel-plugin-macros.`

Ideally, I'd like to contribute an `nx workspace` example to this repo for future reference so what's the best way to start?

- discuss more?
- Add a (broken) example as a PR and iterate there?

I'm in Twin's Discord too if that's easier: `mmoli#0581`

**Comment by mmmoli** [comment]
Figured it out by following the advice here:
https://github.com/kentcdodds/babel-plugin-macros/issues/135#issuecomment-761079720

Would you like me to add an example as I mentioned? twin.macro is super awesome – we should make it as useful to as many people as possible, no?

**Comment by ben-rogerson** [comment]
@mmmoli Great to hear you got around that error!
I'd really like your idea of adding a nx-workspace example!

Would you be happy to add a PR for `twin.examples/nx-workspace-emotion` with minimal code then I can finish it off with a readme?
