### ISSUE TITLE
Nextjs emotion global.css conflicting with GlobalStyle development

### ISSUE THREAD

**Issue by Kalcode** [ben-rogerson/twin.examples#25]
Attempting to use twailwind layers to customize the CSS, but it seems GlobalStyle in development the style get mounted AFTER the custom style. So it gets overridden.

```
@import url('https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&display=swap');

@layer base {
  html {
    @apply font-sans;
  }

  h1 {
    @apply text-2xl;
    @apply font-bold;
  }
  h2 {
    @apply text-xl;
    @apply font-bold;
  }
  h3 {
    @apply text-lg;
    @apply font-bold;
  }
  h4 {
    font-size: 5rem;
  }
}
```

Below is the results

![image](https://user-images.githubusercontent.com/13425721/104220750-910c3c80-5405-11eb-8549-936bc6ebd763.png)

You can see the h4 is lower in specificity. In production when I build it, the sheets are correct it seems.

![image](https://user-images.githubusercontent.com/13425721/104220958-d92b5f00-5405-11eb-83f8-39721a511d40.png)

Curious if you had any ideas on work around OR if this something in GlobalStyle that needs fixed or I am doing something wrong?

Thanks

**Comment by Kalcode** [comment]
Also wanted to note, this issue seems to have started with twin.macro `2.0.8`, downgrading it seems that it render both development and production similar.

It looks like the globals were `base.min.css` and those were loaded before which prevented the conflict.

![image](https://user-images.githubusercontent.com/13425721/104224211-46d98a00-540a-11eb-9834-36dd31189a08.png)

**Comment by ben-rogerson** [comment]
Hey Kalcode, Rather than using layer, I'd suggest using the [Global import from emotion](https://emotion.sh/docs/globals) to create global styles.
This avoids having to load tailwind alongside twin in the same project and should order your globals correctly.

**Comment by Kalcode** [comment]
@ben-rogerson Thanks for the quick response.

I was thinking about that. That issue I am creating is because I am mixing the `css` sheets that nextjs mounts with emotion. Emotion appoarch would be to use `Global`, that does makes sense.

I think the more correct way is to use `theme` and pull them into the `css` in the `Global` using emotion possibly. Like the `theme('fontFamily.sans')` inside the Global instead.

Curious on your thoughts here, I may be misunderstanding, but here `@apply` doesn't work. I think that makes sense. But it would be nice to be able to use the `@apply` but at the same time I think I can get around this by using `theme`.

![image](https://user-images.githubusercontent.com/13425721/104242430-c6745280-5424-11eb-84fc-63fa3cd6c33f.png)

**Comment by ben-rogerson** [comment]
The @layer/@apply directives aren't available here, try this instead:

```js
css`
  @import url('https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&display=swap');

  html {
    ${tw`font-sans`}
  }

  h1 {
    ${tw`text-2xl font-bold`}
  }
  h2 {
    ${tw`text-xl font-bold`}
  }
  h3 {
    ${tw`text-lg font-bold`}
  }
  h4 {
    font-size: 5rem;
  }
}
`
```

If you'd like, you can also write it in css object style which avoids the interpolation brackets, eg: 

```js
{ h1: tw`text-2xl`, h2: tw`text-xl` }
```

**Comment by Kalcode** [comment]
@ben-rogerson awesome, that works also. Makes more sense with this approach vs trying to make the `.css` file load right.

Thanks for helping with this issue, the library and work btw. Much appreciated.
