### ISSUE TITLE
Server Stylesheet Question

### ISSUE THREAD

**Issue by thecodeclimber** [ben-rogerson/twin.examples#26]
I am trying to follow the instructions to add a server stylesheet as noted here:  https://github.com/ben-rogerson/twin.examples/tree/master/next-styled-components#add-the-server-stylesheet

However, my `pages/_document.js` is set up slightly differently then in your example and I am having a hard time figuring out how to mere the two.  Here is how my `pages/_document.js` file looks:

```
import Document, { Html, Head, Main, NextScript } from "next/document";
import { ServerStyleSheet } from "styled-components";

export default class MyDocument extends Document {
  render() {
    return (
      <Html>
        <Head>
          // HEADER SCRIPTS
        </Head>
        <body>
          <noscript>
            // OTHER SCRIPTS
          </noscript>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
```

Any suggestion on how to add a Server Stylesheet to the above code?  

Thanks.

**Comment by ben-rogerson** [comment]
Sure, [check out the Next docs](https://nextjs.org/docs/advanced-features/custom-document) - they seem to have exactly what you're after.
