### ISSUE TITLE
`tw` and `css` props don't work in Goober example

### ISSUE THREAD

**Issue by sampotts** [ben-rogerson/twin.examples#3]
I could be missing something here but I can't get Preact + Goober to work with the `tw` or `css` props. Even the example ends up with the same output:

![image](https://user-images.githubusercontent.com/719092/99927399-5e48af00-2d99-11eb-95af-4e4e1fa9760d.png)

**Comment by ben-rogerson** [comment]
There's some overly light documentation for Goober + Twin at the moment - sorry about that.

Currently Goober doesn't offer a css prop so you'd need to use styled-components as the example uses.

**Works**
- styled import
- tw import

**Doesn’t**
- tw prop
- css prop
- tw.div shorthand

**Comment by sampotts** [comment]
All good 👍 I'd love to help out but wouldn't know where to start with it. Goober looks great, being so small. I can work around these limitations for now 👍

**Comment by ben-rogerson** [comment]
Oh yeah, and when you couple it with Preact then you're cooking 👍

**Comment by sampotts** [comment]
One more thing, I noticed I get a TypeScript warning/error when using `styled`. Any ideas? 

![image](https://user-images.githubusercontent.com/719092/101300954-6de0f100-388b-11eb-95bf-f0941ddaba7f.png)

I have a `twin.d.ts` containing this:

```js
import 'twin.macro';

import { css as cssImport, styled as styledImport } from 'goober';

declare module 'twin.macro' {
  // The styled and css imports
  const styled: typeof styledImport;
  const css: typeof cssImport;
}

// The 'as' prop on styled components
declare global {
  namespace JSX {
    interface IntrinsicAttributes<T> extends DOMAttributes<T> {
      as?: string;
    }
  }
}
```

**Comment by ben-rogerson** [comment]
Hey Sam, I've got no immediate ideas but does the "styled.div" syntax throw the same error?

**Comment by sampotts** [comment]
I did try that but it throws:

> Property 'div' does not exist on type 'StyledFunction'.ts(2339) 

The `styled('div')` syntax works, it just throws a TypeScript error so it probably requires some hacking of the types I think.

**Comment by ben-rogerson** [comment]
If you come up with anything please let me know :) I'd assist but I'm not great with this topic.

**Comment by sampotts** [comment]
I'll have a tinker and see what I can come up with.
