### ISSUE TITLE
twin.macro: Cannot find module '../colors'

### ISSUE THREAD

**Issue by esh2n** [ben-rogerson/twin.examples#31]
https://github.com/ben-rogerson/twin.examples/tree/master/next-emotion#installation

I followed this tutorial in README.
And when I use `tailwind.config.js` full config ,I got this error,

```
twin.macro: Cannot find module '../colors'
```

It's because of that we doesn't have colors.js file.

solution: just add colors.js in dir

https://raw.githubusercontent.com/tailwindlabs/tailwindcss/master/colors.js

**Comment by ben-rogerson** [comment]
Ah, yes I see! You must have used the full config option:

```shell
curl https://raw.githubusercontent.com/tailwindcss/tailwindcss/master/stubs/defaultConfig.stub.js > tailwind.config.js
```

Which has given you a tailwind.config.js containing this:

```js
const colors = require('../colors')

module.exports = {
  // ...
  theme: {
    // ....
    colors: {
      transparent: 'transparent',
      current: 'currentColor',

      black: colors.black,
      white: colors.white,
      gray: colors.coolGray,
      red: colors.red,
      yellow: colors.amber,
      green: colors.emerald,
      blue: colors.blue,
      indigo: colors.indigo,
      purple: colors.violet,
      pink: colors.pink,
    },

// ...
```

So I'll need to update those instructions.

To generate a full config now, you'll need to run:

```
npx tailwindcss-cli@latest init --full
```

**Comment by esh2n** [comment]
@ben-rogerson 

Thanks.
It's absolutely solved.
