### ISSUE TITLE
Vite examples

### ISSUE THREAD

**Issue by iwgx** [ben-rogerson/twin.examples#33]
Hello, I would like to know how to integrate `twin.macro` with `Vite`

Just tried it before but I got an issue here https://github.com/vitejs/vite/issues/1942

Thanks before

**Comment by ben-rogerson** [comment]
I had a crack at it too but hit the same roadblock - some googling came up with the replace plugi to remove `process.platform` but it doesn't seem to work. It may not be supported with Vite?

```js
// vite.config.ts
import reactRefresh from '@vitejs/plugin-react-refresh'
import { babel } from '@rollup/plugin-babel';
import replace from '@rollup/plugin-replace';
import { defineConfig } from 'vite'

export default defineConfig({
  plugins: [reactRefresh(),],
  build: {
    rollupOptions: {
      plugins: [
        replace({
            'process.platform': JSON.stringify('win32')
        }), 
        babel({ babelHelpers: 'bundled' })
      ]
    }
  }
})
```

**Comment by iwgx** [comment]
Ah, I see. Thanks for looking into it.
