### ISSUE TITLE
next + styled components example does not work

### ISSUE THREAD

**Issue by jasonkuhrt** [ben-rogerson/twin.examples#34]
![image](https://user-images.githubusercontent.com/284476/107515551-2c194300-6b79-11eb-964f-ab26255262ca.png)

**Comment by ben-rogerson** [comment]
Which example did you try?

**Comment by jasonkuhrt** [comment]
https://github.com/ben-rogerson/twin.examples/tree/master/next-styled-components

**Comment by RangerCoder99** [comment]
Same issue here, just copy the main example

**Comment by ben-rogerson** [comment]
Should be fixed now, just needed a version bump.

**Comment by ben-rogerson** [comment]
Feel free to reopen if there happens to still be an issue 👍
