### ISSUE TITLE
[component-library-emotion] can't overwrite the config in components with the config in app

### ISSUE THREAD

**Issue by locona** [ben-rogerson/twin.examples#43]
**component-library-emotion**

Currently, I can't overwrite the config(ex colors) set in components with the config set in app.

```
app/tailwind.config.js
components/tailwind.config.js
```

Do you know the best way to solve this problem?

From what I have found, defining the following on the components side may work.
I will test this in the future.

components/tailwind.config.js
````
module.exports = {
  theme: {
    colors: {
      red: {
        medium: '#e53e3e',
        dark: '#742a2a'
      },
      blue: {
        medium: '#3182ce',
        dark: '#2a4365'
      },
      'th-primary': 'var(--primary)',
      'th-secondary': 'var(--secondary)'
    }
  }
}
````

components/index.css
``` components/index.css
:root {
  --primary: theme('colors.red.dark');
  --secondary: theme('colors.red.medium');
}
 
.th-blue {
  --primary: theme('colors.blue.dark');
  --secondary: theme('colors.blue.medium');
}
````

**Comment by ben-rogerson** [comment]
Hey Iocona 👋 

Multiple tailwind configs are too much work - I think with these component libraries there should only be a single tailwind config at root level. What are your thoughts on this?

Anyway, you should be able to set the colors in that tailwind.config.js using css variables:

```js
// tailwind.config.js
module.exports = {
  theme: {
    colors: {
      red: {
        medium: 'var(--primary)',
      },
    }
  }
}
```

Then you add that class to your component in the components folder.

Then you'll need to set the default `--primary` variable at :root / body level in your app - I prefer to do this using the `Global` import. 

Then when you want to change the theme, you can then change the variable globally like this:

```js
import { Global } from '@emotion/react';

const Component = () => (
    <Global
        styles={{
            ':root' { '--primary': 'green' },
        }}
    />
);
```

Let me know how it goes!

**Comment by ben-rogerson** [comment]
Hey Iocona, I recently upgraded the [component-library-styled-components](https://github.com/ben-rogerson/twin.examples/tree/master/component-library-styled-components) example to use a single babel process with auto component updates - thought you might be interested.
