### ISSUE TITLE
[next-styled-components] initial styles empty on production build

### ISSUE THREAD

**Issue by aynik** [ben-rogerson/twin.examples#48]
When I run the `next-styled-components` example with `yarn dev` the initial styles load fine but when building and serving the initial styles are gone, please check the screenshot for the experienced behavior.

![Screen Shot 2021-03-03 at 14 00 36](https://user-images.githubusercontent.com/33802811/109755531-8ada5580-7c29-11eb-8652-5d13b2819ba4.png)

**Comment by ben-rogerson** [comment]
They're working as I can see them being applied in the styles panel:
![image](https://user-images.githubusercontent.com/21288568/110017171-d39f2500-7d75-11eb-8127-f415b4a5fbfd.png)

Not sure why we can't see them in the devtools - they seem to be injected into the same style container that you're observing in the screenshot 🤷‍♂️

**Comment by aynik** [comment]
Thanks for checking, you're right and furthermore the styles on production can be retrieved via:

```javascript
document.querySelector('style[data-styled]').sheet.cssRules
```
