### ISSUE TITLE
React is not defined (NextJs,emotion,typescript)

### ISSUE THREAD

**Issue by neilnahid** [ben-rogerson/twin.examples#5]
Steps to reproduce:
1. Follow guide https://github.com/ben-rogerson/twin.examples/tree/master/next-emotion
2. Visit any page
3. See Error
![image](https://user-images.githubusercontent.com/25801890/100403675-7884d480-309a-11eb-96f3-963f04e7a808.png)

I think it has something to do with shorthand for React.Fragments

**Comment by ben-rogerson** [comment]
Have you tried adding `import React from 'react'` at the top?

**Comment by neilnahid** [comment]
I followed the updated documentation and it seems to work now but to answer your question, yes it works but I need to import React from every component that is used by the page. I might also have messed up my .babelrc config. I followed this issue https://github.com/vercel/next.js/issues/18096 and it turns out, it has something to do with emotion or something 🤷‍♂️

**Comment by luknl** [comment]
Same problem here! Fixed it by adding this code in the `.babel.js` (using Emotion 11 here)
```
module.exports = {
  presets: [
    [
      'next/babel',
      {
        'preset-react': {
          runtime: 'automatic',
          importSource: '@emotion/react',
        },
      },
    ],
  ],
  plugins: ['@emotion/babel-plugin', 'babel-plugin-macros'],
};
```

**Comment by ben-rogerson** [comment]
Might be worth adding that to the example, who wants those damn react imports nowadays :D

**Comment by ben-rogerson** [comment]
Worth noting is that this only works with `.babelrc.js` and doesn't if you have a config named `.babelrc`.

**Comment by a-eid** [comment]
@ben-rogerson @luknl it deesn't work with vite.

**Comment by ben-rogerson** [comment]
@a-eid In vite the babel config can be added in [vite.config.js/ts](https://github.com/ben-rogerson/twin.examples/blob/master/vite-styled-components-typescript/vite.config.ts#L8)

**Comment by a-eid** [comment]
@ben-rogerson thanks, will try it out later today.
