### ISSUE TITLE
Documentation for webpack5

### ISSUE THREAD

**Issue by kodai3** [ben-rogerson/twin.examples#50]
Using with Next.js with webpack 5 enabled, I noticed as of webpack5 we cannot configure polyfill for `fs` with [this](https://github.com/ben-rogerson/twin.examples/tree/master/next-emotion#add-the-next-config).

ref: https://webpack.js.org/configuration/node/

I think with webpack5 we should do like this.
```
// next.config.js
module.exports = {
  webpack: (config, { isServer }) => {
    // Fixes packages that depend on fs/module module
    if (!isServer) {
      config.resolve = {
        fallback: {
          fs: 'empty', 
          module: 'empty'
        },
      }
    }

    return config
  },
}
```

I thought adding `<details>` section for this would be great.

Thank you for great tools and examples!

**Comment by ben-rogerson** [comment]
Thanks for sharing this info and for the fix too.
I've updated the [emotion](https://github.com/ben-rogerson/twin.examples/tree/master/next-emotion#add-the-next-config) + [styled-components](https://github.com/ben-rogerson/twin.examples/tree/master/next-styled-components#add-the-next-config) examples with this fix

Feel free to let me know if there’s anything I’ve missed. cheers  👍

**Comment by HellBlazer616** [comment]
I just tried to use the webpack5 configuration and were getting errors. I think new configuration would look something like this: 

```js
module.exports = {
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.resolve.fallback.fs = false;
    }
    return config;
  },
}
```
reference: https://github.com/vercel/next.js/issues/7755#issuecomment-812805708

**Comment by outerlook** [comment]
@HellBlazer616, I could get dev server running with this too. But have you been able to compile the production build? 
I've got this error:
`
ModuleNotFoundError: Module not found: Error: Can't resolve 'module' in 'project_path\node_modules\import-fresh\node_modules\resolve-from'
` 
I've tried also tweaking `module` to `'empty'`, both to empty and both to false.

Has anyone been struggling with that too?

**Comment by HellBlazer616** [comment]
@outerlook With the config I provided I am able to compile for production. But that site is mostly for internal use and all the data is fetched client side. So, I am not sure if its going to compile for all builds. with SSR, SSG or ISR. That's why we are still on webpack 4 on our main site. Maybe the module will be false like the "fs". 

But don't quote me on that. I absolutely know nothing about webpack.

**Comment by ben-rogerson** [comment]
Hey guys, I switched to webpack5 in the [next-emotion example](https://github.com/ben-rogerson/twin.examples/tree/master/next-emotion) and each of the modes: dev/start/build/export ran without an issue.

Here's the config I used: 

```js
module.exports = {
  future: {
    webpack5: true,
  },
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.resolve.fallback = {
        fs: false,
        module: false,
      }
    }

    return config
  },
}
```

Related https://github.com/storybookjs/storybook/issues/4082#issuecomment-818032557
