### ISSUE TITLE
Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by Blackglade** [ben-rogerson/twin.examples#57]
### Overview

Hi, So I'm running a recently created NextJS App w/ Emotion + Tailwindcss and followed this guide: https://github.com/ben-rogerson/twin.examples/tree/master/next-emotion but it doesn't seem to work.

System Information:
Node: 16.0.0
Npm: 7.10.0

Here are the steps I took: 

1. Installed NextJS via create-next-app and migrated over to typescript.
2. Ran `npm install @emotion/react @emotion/styled @emotion/css @emotion/server` which worked fine.
3. Then I ran: `npm install -D twin.macro tailwindcss @emotion/babel-plugin babel-plugin-macros` which failed because of this error:

```
npm ERR! Found: postcss@8.1.7
npm ERR! node_modules/postcss
npm ERR!   postcss@"8.1.7" from next@10.1.3
npm ERR!   node_modules/next
npm ERR!     next@"10.1.3" from the root project
npm ERR!   peer postcss@"^8.0.9" from tailwindcss@2.1.1
npm ERR!   node_modules/tailwindcss
npm ERR!     dev tailwindcss@"*" from the root project
npm ERR!     tailwindcss@"^2.0.1" from twin.macro@2.3.3
npm ERR!     node_modules/twin.macro
npm ERR!       dev twin.macro@"*" from the root project
npm ERR!   2 more (autoprefixer, postcss-js)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer postcss@"^8.1.13" from postcss-nested@5.0.5
npm ERR! node_modules/tailwindcss/node_modules/postcss-nested
npm ERR!   postcss-nested@"5.0.5" from tailwindcss@2.1.1
npm ERR!   node_modules/tailwindcss
npm ERR!     dev tailwindcss@"*" from the root project
npm ERR!     1 more (twin.macro)
npm ERR! 
```

so I figured that tailwind still needed postcss and it's config file. So I ran the following:

4. `npm install -D tailwindcss@latest postcss@latest autoprefixer@latest` which resolved the post css fix.
5. Then I reran the command in #2: `npm install -D twin.macro tailwindcss @emotion/babel-plugin babel-plugin-macros` and it worked perfectly.
6. Then I edited my `_app.js` file to do this:
```
import { GlobalStyles } from 'twin.macro'

export default function MyApp({ Component, pageProps }) {
  return <><GlobalStyles /><Component {...pageProps} /></>
}
```

7. Finally I did `npm run dev` and I'm getting the following issue:

```
error - ./node_modules/cosmiconfig/dist/readFile.js:9:0
Module not found: Can't resolve 'fs'
null
error - ./node_modules/cosmiconfig/dist/readFile.js:9:0
Module not found: Can't resolve 'fs'
null
```

Why is this occuring and also why does your instructions never include the postcss install portion as well as autoprefixer from tailwind's website.

**Comment by locona** [comment]
Do you have this set up?

https://github.com/ben-rogerson/twin.examples/blob/master/next-emotion/next.config.js

**Comment by Blackglade** [comment]
Thanks this resolved it!

**Comment by rottitime** [comment]
> Do you have this set up?
> 
> https://github.com/ben-rogerson/twin.examples/blob/master/next-emotion/next.config.js

The file is removed (404). Can you please repost the fix here? @locona @Blackglade

**Comment by ben-rogerson** [comment]
Updated the link above with a permalink 👍

**Comment by ameshkin** [comment]
I use blitz js, and this simply is not working. It doesn't work in next config or blitz config
