### ISSUE TITLE
component-library-emotion: webpack5 not working 

### ISSUE THREAD

**Issue by locona** [ben-rogerson/twin.examples#58]
I am trying to use webpack5 for "component-library-emotion".

However, I am getting the following error.

**Error Message**
```
Error: Cannot find module 'components'
```

The only changes I made were.
ref: https://github.com/ben-rogerson/twin.examples/issues/50#issuecomment-821785675
```
// next.config.js

module.exports = {
  future: {
    webpack5: true,
  },
  webpack: (config) => {
    config.resolve.fallback = {
      fs: false,
      module: false,
    }

    return config
  },
}
```

What other changes do you think are needed?

**Comment by locona** [comment]
I think we may have solved it.

I'll post a PR as soon as I sort it out.

**Comment by ben-rogerson** [comment]
Looks like there were a few issues with the example.

I've just added [a few tweaks](https://github.com/ben-rogerson/twin.examples/commit/8ba7977a08e8e82db4332529f2c14a9f1452edb3) to the example.

I've now made the components `packages/components/dist` folder available before yarn links `packages/components` into `packages/app`.

Please let me know if that fixes the issue.

**Comment by locona** [comment]
It worked fine!

Thank you!
