### ISSUE TITLE
`tw` and `css` props don't work in stitches example

### ISSUE THREAD

**Issue by frencojobs** [ben-rogerson/twin.examples#60]
I've found that only styled-components made using the `styled` syntax from stitches are working. The `tw` and `css` props are not working at all. Here is the generated output.
![2021-05-23_18-29](https://user-images.githubusercontent.com/17830687/119259603-03333000-bbf5-11eb-90e7-009d232e8f88.png)

I use the latest versions for both stitches and twin.

**Comment by ben-rogerson** [comment]
I'm going to see what can be done to improve support, but for now, twin’s css and tw props aren’t supported because stitches uses an alternative syntax.

**Comment by alanontheweb** [comment]
This would be awesome. Thanks @ben-rogerson

**Comment by ben-rogerson** [comment]
I had another look at this and I found there is now better support for the css prop in Stitches.

That also means that Twin's tw prop works (tw converts to the css prop under the hood).

## Using the tw prop

```js
import tw from "twin.macro";
import { styled } from '../stitches.config'

const Button = styled('button', {})

const Component = () => <Button tw="bg-black text-white">Send</Button>
```

## Using the css prop

```js
import tw from "twin.macro";
import { styled } from '../stitches.config'

const Button = styled('button', {})

const styles = ({ isSecondary }) => ({
  ...(isSecondary && tw`bg-blue-500`),
  ...tw`bg-black text-white`,
})

const Component = ({ isSecondary }) => (
  <Button css={styles({ isSecondary })}>Send</Button>
)
```

@alanontheweb I'm guessing you hit an issue with this somewhere?

**Comment by alanontheweb** [comment]
@ben-rogerson ah this helps! I do wish there was support for the tw prop on jsx elements, as it's often the case that I'm working on some one-off container or just general scaffolding and it's a bit cumbersome to predefine a styled component. Do you think this support could come down the road from twin / stitches? Or is there a recommended pattern, like importing a box component as a replacement for a div? (still not as convenient as applying `tw` directly on jsx elements though...)

Thank you!

**Comment by alanonthegit** [comment]
@ben-rogerson also do you have a recommendation around injecting the globalStyles? Last I checked the repo, it wasn't implemented and wasn't sure what the best solution would be or if it was something twin would eventually provide.

**Comment by ben-rogerson** [comment]
> the tw prop on jsx elements... Do you think this support could come down the road from twin / stitches?

Sure do - this is definitely on my list of features to add.

Stitches needs more features patched than the current list of supported css-in-js packages.  
I don’t want to add more bloat to the main twin.macro repository so I'm going to shift most of it into another package.

> do you have a recommendation around injecting the globalStyles?

What's in the example is my current recommendation - but I'm working on improvements here over the next week or two.

--- 

I'll set up a new discussion so you can follow the progress 👍

**Comment by alanonthegit** [comment]
Oh awesome! thank you :)

Do you mean the example above? I was wondering how to import tailwind's pre-flight, and remembered that <GlobalStyles /> was used in the emotion example for Gatsby. Not sure if there is an equivalent for that.

**Comment by ben-rogerson** [comment]
Yeah I mean in [the stitches example](https://github.com/ben-rogerson/twin.examples/tree/master/next-stitches-typescript).

The GlobalStyles import usually takes care of the reset + pre-flight styles but in Stitches case, the existing configuration doesn't work so I've added them manually instead in the v1 of the integration. It's not great because we miss out on a few dynamic parts of the global styles + `addBase` styles within plugins are also missed.

Next version of twin will allow stitches imports `styled`, `css`, `globalStyles` (new import) to be routed through twin.macro and the pre-flight styles etc will be exposed for use with stitches `global` import.

eg: 

```js
import { globalStyles } from "twin.macro";

const globals = global(globalStyles);

() => {
   globals();

   return <div />;
};
```

**Comment by alanontheweb** [comment]
Ah got it! Yeah, I ended up rolling out a similar temporary solution in the meantime but will update to this approach when it's ready.

One final question and in no way meant as pressure - As I'm starting a new project with twin+stitches, I wanted to ask if the effort to support the  `tw` prop in JSX elements was small or large, and if it made sense to wait for it in the near term or work around it for now and refactor later (looking to minimize refactoring if possible).

Thanks again for the prompt responses and as always, appreciate your time.

**Comment by ben-rogerson** [comment]
>I wanted to ask if the effort to support the tw prop in JSX elements was small or large,

I'd put it in the 'small' category.
I'm aiming to push the full integration out within 1-2 weeks.

So we're on the same page, twin will turn this:

```js
import 'twin.macro'

;<div tw="block" randomProp={true} />
```

Into this:

```js
import { styled } from "./../stitches.config";

const GeneratedName = styled('div', { display: 'block' })

;<GeneratedName randomProp={true} />
```

There's not much different, so refactors _shouldn't_ be too much of an issue - I'd say press on with it 👍

**Comment by alanontheweb** [comment]
Awesome! Yep, I started with that approach. Looking forward to the update and thank you :D

**Comment by alanontheweb** [comment]
Hi @ben-rogerson just noticed that plugin support is not yet available after not having luck implementing `line-clamp` utilities. When you mentioned "full integration" above, does that also include plugins or is that a separate effort?

**Comment by ben-rogerson** [comment]
Yes, plugin support will be added at the same time 👍

**Comment by ben-rogerson** [comment]
Hey folks, I've just pushed a new version (twin.macro@2.6.1) which adds improved support for twin + stitches 🎉🎉🎉 

I've also updated the [stitches typescript example](https://github.com/ben-rogerson/twin.examples/tree/master/next-stitches-typescript) with new usage examples, new types, and a new readme.

Make sure you also check out the [PR for more info](https://github.com/ben-rogerson/twin.macro/pull/471)

Enjoy ✌️
