### ISSUE TITLE
Style flickering occurring in Next.js app

### ISSUE THREAD

**Issue by dspacejs** [ben-rogerson/twin.examples#71]
I followed the Next.js + Emotion guide.

This is my `_document` file:

```tsx
/* eslint-disable react/no-danger */
import React from "react";
import Document, {
  Html,
  Head,
  Main,
  NextScript,
  DocumentContext,
  DocumentInitialProps,
} from "next/document";
import { extractCritical } from "@emotion/server";

interface Props {
  css: string;
  ids: string[];
}
class CustomDocument extends Document<Props> {
  static async getInitialProps(ctx: DocumentContext): Promise<DocumentInitialProps> {
    const initialProps = await Document.getInitialProps(ctx);
    const page = await ctx.renderPage();
    const styles = extractCritical(page.html);
    return { ...initialProps, ...page, ...styles };
  }

  render(): React.ReactElement {
    return (
      <Html lang="en">
        <Head>
          <link rel="shortcut icon" href="/favicon.svg" />
          <style
            data-emotion-css={this.props.ids.join(" ")}
            dangerouslySetInnerHTML={{ __html: this.props.css }}
          />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default CustomDocument;
```

And I added `<GlobalStyles />` to my `_app` file. 

This is my `.babelrc.js`:

```js
module.exports = {
  presets: [
    [
      "next/babel",
      {
        "preset-react": {
          runtime: "automatic",
          importSource: "@emotion/react",
        },
      },
    ],
  ],
  plugins: [
    "@emotion/babel-plugin",
    "babel-plugin-macros",
    "@babel/plugin-proposal-export-namespace-from",
  ],
};
```

So it's all set up according to the instructions. There is no flickering in development, which is fine.

However, in production, `_document` isn't setting the critical Emotion styles. It has the `<style>` tag:

```html
<style data-emotion-css=""></style>
```

But the styles are empty. I'm not sure why this is.

**Comment by ben-rogerson** [comment]
This would be an issue with Emotion rather than Twin, best to check their docs/issues on this.

**Comment by ben-rogerson** [comment]
@dspacejs I've updated the next + emotion examples with the new SSR style strategy - check the `pages/_document` files.

**Comment by dspacejs** [comment]
@ben-rogerson I've tried implementing exactly what you did, but I still have the same problem. When the page first loads, the styles stutter.

Did you try this in production, with `next build` and `next start`? 

I checked the dev server and the styles are being set in the `<head>` tag:

```html
<style data-emotion="css-global" data-s="">...</style>
```

But for some reason in production, it's not working.

**Comment by ben-rogerson** [comment]
That's strange, I've tested that config on a production site and on the examples with no flickering issues. 
I also disabled JavaScript and the styles render just as the hydrated app.

To help narrow this down, is the flickering happening with all styles or just certain ones?

**Comment by dspacejs** [comment]
@ben-rogerson actually hold on, sorry, I don't think this is an issue with twin.macro styles.

Basically I was using both `className` and `twin.macro` styles. I overlooked the fact one of the components with flickering styles was using a `className` prop.

I'm moving everything in this project over to twin.macro anyway, so it should just work. But I'll let you know if I come across any other problems.

Thanks for the help
