### ISSUE TITLE
Starter kit for vite + styled-components seems broken with blank page

### ISSUE THREAD

**Issue by TeaBough** [ben-rogerson/twin.examples#77]
If I clone the starter from https://github.com/ben-rogerson/twin.examples/tree/master/vite-styled-components-typescript
and run : 
```npm install && npm run dev```

I get a blank page. And in the console, this nice error : 
```
Logo.tsx:24 Uncaught ReferenceError: _cssPropImport is not defined
    at Logo.tsx:24
```

It's only the case for the starter kit with styled-components, the one with emotion seems fine.

**Comment by ben-rogerson** [comment]
Thanks for the heads up here. 
I've updated the example and readme instructions with a working config.

**Comment by TeaBough** [comment]
Awesome ! Thanks @ben-rogerson
