### ISSUE TITLE
Uncaught ReferenceError: _styled is not defined in styled-components starter kit

### ISSUE THREAD

**Issue by TeaBough** [ben-rogerson/twin.examples#78]
If I modify a bit the styled-component starter kit to add a custom component and wrap it I get this error :

```
Uncaught ReferenceError: _styled is not defined
    at App.tsx:37
```

```
const Test = function() {
  return <div>HAHHAHAH</div>
}
const Wrapped = styled(Test)`
  ${tw`bg-blue-500`}
`
```

**Comment by ben-rogerson** [comment]
Hey there
 
The component you're wrapping with `styled` should be a styled component.

Try something like this:

```js
const Test = tw.div``
const Wrapped = styled(Test)`
  ${tw`bg-blue-500`}
`
;<Wrapped>HAHHAHAH</Wrapped>
```

Here's some more details about [extending components →](https://github.com/ben-rogerson/twin.macro/blob/master/docs/styled-component-guide.md#extending-components)
