### ISSUE TITLE
GlobalStyles import in emotion.ts example wrong

### ISSUE THREAD

**Issue by wottpal** [ben-rogerson/twin.examples#79]
In _app.tsx of the new emotion (ts) example `GlobalStyles` is imported from `twin.macro` but should be imported from the local definition instead.

See https://github.com/ben-rogerson/twin.examples/blob/master/next-emotion-typescript/pages/_app.tsx.

I didn't check other example, it might be wrong there, too.

Correct: 

```
import GlobalStyles from '../styles/GlobalStyles'
```

**Comment by ben-rogerson** [comment]
Hey Dennis, thanks heaps for the heads up here - I've now updated the import path.
