### ISSUE TITLE
Babel macros fails

### ISSUE THREAD

**Issue by sh4d1t0** [ben-rogerson/twin.examples#84]
Hello, I have an issue with Parcel 2 and babel macros, I tried the documentation but I have this issue:

<img width="1672" alt="image" src="https://user-images.githubusercontent.com/11230995/153114058-d6fb157d-c0e7-429f-a9ef-c07db6acd637.png">

Can somebody help me?

**Comment by ben-rogerson** [comment]
That error shows when the babel config isn't being picked up. 
(Assuming `babel-plugin-macros` has been added to your babel config).

I've just updated the [parcel + styled-components example](https://github.com/ben-rogerson/twin.examples/tree/master/react-styled-components) so you can see what's required.

**Comment by sh4d1t0** [comment]
It's not working.. I'm using typescript and emotion

My Versions:

dev:
"@emotion/react": "^11.7.1"
"@emotion/styled": "^11.6.0"
"typescript": "^4.5.5"

devDependencies:
"twin.macro": "^2.8.2"
"babel-plugin-macros": "^3.1.0"
"@babel/plugin-transform-react-jsx": "^7.16.7"
"@emotion/babel-plugin": "^11.7.2"
"parcel": "^2.2.1"

I installed "@types/babel-plugin-macros": "^2.8.5" but didn't work

My babelrc

{
  "presets": ["@babel/preset-typescript"],
  "plugins": ["babel-plugin-macros", "@emotion", "@babel/plugin-transform-react-jsx"]
}

I was trying with "plugins": ["macros" ...] too, but I have the same issue, so I changed the babel-plugin-macros with 2.8.0... but don't work

My environment is:
node - 16.13.2
npm - 8.4.0

**Comment by ben-rogerson** [comment]
Is the [twin example](https://github.com/ben-rogerson/twin.examples/tree/master/react-styled-components) not working for you? The installs you pasted looks good to me.

**Comment by sh4d1t0** [comment]
Hello, I'm trying Install with a clean install, only react with typescript, tailwind, emotion and twin.macro, but now I have the next issues when I am running my proyect:

<img width="983" alt="image" src="https://user-images.githubusercontent.com/11230995/153289797-cc607e01-6337-47bd-b8d5-9e6498368ed7.png">
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/11230995/153289964-e148c63b-f08e-4ad8-b57e-0a0f3ccd31f4.png">
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/11230995/153290029-c52ab02f-a500-488c-ba4b-f0171b59e6f8.png">

And finally brocken my package.json (delete all), I don't know if something change on Parcel or babel-plugin-macros

My .babelrc
`{
  "plugins": [
    "babel-plugin-macros",
    "babel-plugin-twin",
    [
      "@emotion/babel-plugin-jsx-pragmatic",
      {
        "export": "jsx",
        "import": "__cssprop",
        "module": "@emotion/react"
      }
    ],
    [
      "@babel/plugin-transform-react-jsx",
      {
        "pragma": "__cssprop"
      }
    ]
  ]
}`

I was trying uninstall babel-plugin-twin too, with babel/plugin-transform-react-jsx passing auto too, uninstall emotion/babel-plugin-jsx-pragmatic too, with emotion-plugin-macro too, without GlobalStyles.tsx just passing twin.macro, and nothing works I have the same issues always

<img width="737" alt="image" src="https://user-images.githubusercontent.com/11230995/153293114-74f665dc-fba2-4813-9984-4794413dcd4b.png">

**Comment by sh4d1t0** [comment]
> Is the [twin example](https://github.com/ben-rogerson/twin.examples/tree/master/react-styled-components) not working for you? The installs you pasted looks good to me.

This Example works fine... but it's with styles-components, I was trying using emotion(ts)

**Comment by sh4d1t0** [comment]
Great! now works fine,

It was my tsconfig.json
