### ISSUE TITLE
Can't resolve 'tailwindcss/dist/base.min.css'

### ISSUE THREAD

**Issue by Blazekla** [ben-rogerson/twin.examples#9]
I have followed the Next-Emotion example Readme to update twin.macro v1.12.0 to v2.0.4.

I receive the following error when running the dev script:

>error - ./pages/_app.js
>Module not found: Can't resolve 'tailwindcss/dist/base.min.css' in 'X:\Programming\\{....}\pages'

Current dependencies
```
"scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
 "dependencies": {
    "@emotion/babel-preset-css-prop": "^11.0.0",
    "@emotion/css": "^11.0.0",
    "@emotion/react": "11.0.0",
    "@emotion/styled": "^11.0.0",
    "next": "latest",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "twin.macro": "^2.0.4"
  },
```

When adding the tailwindcss package (like the Next-Emotion example) the app works.

This is currently not included in the Readme. I'm not sure if this is something that needs to be included or just a bug on my end.

**Comment by george-dotdev** [comment]
Same on Vanilla react emotion.

**Comment by ben-rogerson** [comment]
Looks like yarn keeps the `tailwindcss`dependency in a `node_modules` subfolder.
I'll fix this the next version.

For now, either install `yarn add tailwindcss` or use npm to install `npm install twin.macro`

**Comment by ben-rogerson** [comment]
I'm recommending tailwindcss be installed now. This will avoid the error.
